# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leaf inclination distribution function
#' cummulative lagden function from Wout Verhoef's dissertation
#' Extended here for any angle  
#'
#' @param a parameter
#' @param b parameter
#' @param theta angle in degrees
#' @return angle fraction value
#'
#' @export
cdcum <- function(a, b, theta) {
    .Call('_ccrtm_cdcum', PACKAGE = 'ccrtm', a, b, theta)
}

#' Leaf inclination distribution function
#' Ellipsoidal distribution function
#'
#' @param ala average leaf angle parameter
#' @param tx1 angle in degree
#' @param tx2 angle in degree
#' @return angle fraction value
#'
#' @export
cambell <- function(ala, tx1, tx2) {
    .Call('_ccrtm_cambell', PACKAGE = 'ccrtm', ala, tx1, tx2)
}

#' plate model 
#'
#' @param(theta) Angle (in radians!)
#' @param(ref) refractive index
#' 
#' @references Feret et al. (2008), PROSPECT-4 and 5: Advances in the Leaf Optical
#' Properties Model Separating Photosynthetic Pigments, Remote Sensing of
#' Environment
#' @references Stern F. (1964), Transmission of isotropic radiation across an
#' interface between two dielectrics, Appl. Opt., 3(1):111-113.
#' @references Allen W.A. (1973), Transmission of isotropic light across a
#' dielectric surface in two and three dimensions, J. Opt. Soc. Am.,
#' 63(6):664-666.
#' 
#' @export
cplateModel <- function(r12, t12, r21, t21, x, y, trans, N) {
    .Call('_ccrtm_cplateModel', PACKAGE = 'ccrtm', r12, t12, r21, t21, x, y, trans, N)
}

#' tav function
#' 
#' Stern F. (1964), Transmission of isotropic radiation across an
#' interface between two dielectrics, Appl. Opt., 3(1):111-113.
#' Allen W.A. (1973), Transmission of isotropic light across a
#' dielectric surface in two and three dimensions, J. Opt. Soc. Am.,
#' 63(6):664-666.
#' @references Feret et al. (2008), PROSPECT-4 and 5: Advances in the Leaf Optical
#' Properties Model Separating Photosynthetic Pigments, Remote Sensing of
#' Environment
#' 
#' @param(theta) Angle (in degrees!)
#' @param(ref) refractive index
#' @export
ctav <- function(theta, n) {
    .Call('_ccrtm_ctav', PACKAGE = 'ccrtm', theta, n)
}

cJfunc1 <- function(k, l, t) {
    .Call('_ccrtm_cJfunc1', PACKAGE = 'ccrtm', k, l, t)
}

cJfunc2or3 <- function(k, l, t) {
    .Call('_ccrtm_cJfunc2or3', PACKAGE = 'ccrtm', k, l, t)
}

cJfunc4 <- function(m, t) {
    .Call('_ccrtm_cJfunc4', PACKAGE = 'ccrtm', m, t)
}

#' Single layer reflection and transmission function 
#' 4sail
#' \code{cReflTrans} calculates
#' @param rho numeric vector of particle reflectance
#' @param tau numeric vector of particle transmission
#' @param lai leaf area index
#' @param att 
#' @param m
#' @param sigb
#' @param ks
#' @param ko
#' @param sf
#' @param sb
#' @param vf
#' @param vb
#' 
#' @author Marco D. Visser
#' @return Returns a list of reflectances
#' @export
cReflTrans <- function(rho, tau, lai, att, m, sigb, ks, ko, sf, sb, vf, vb) {
    .Call('_ccrtm_cReflTrans', PACKAGE = 'ccrtm', rho, tau, lai, att, m, sigb, ks, ko, sf, sb, vf, vb)
}

#' Single layer for two layer prospect
#' 4sail2
cReflTransSingleLayer <- function(rho, tau, lai, ks, ko, sdf, sdb, dof, dob, sob, sof, ddb, ddf) {
    .Call('_ccrtm_cReflTransSingleLayer', PACKAGE = 'ccrtm', rho, tau, lai, ks, ko, sdf, sdb, dof, dob, sob, sof, ddb, ddf)
}

